name: Auto PR from Master to Develop

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  create-pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Create a pull request using GitHub CLI
        run: |
          gh pr create \
            --base develop \
            --head master \
            --title "Sync Master to Develop" \
            --body "Automatically created PR to sync changes from Master to Develop."
